version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password

